# Generated by Django 4.1.3 on 2022-11-30 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="cervix-images")),
                ("prediction", models.CharField(blank=True, max_length=20)),
                ("validated", models.BooleanField(default=False)),
                ("doneAt", models.DateTimeField(auto_now_add=True)),
                ("dateModify", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Diagnostic",
                "verbose_name_plural": "Diagnostic",
                "db_table": "",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Docteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=50)),
                ("email", models.CharField(blank=True, max_length=50)),
                ("hopital", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Speculum",
                "verbose_name_plural": "Speculums",
                "db_table": "",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localite", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "db_table": "",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone", models.CharField(max_length=50)),
                ("adresse", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50)),
                ("diagnostic", models.ManyToManyField(to="surveillance.diagnostic")),
                (
                    "docteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveillance.docteur",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveillance.patient",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveillance.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier",
                "verbose_name_plural": "Dossiers",
                "db_table": "",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="docteur",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveillance.service"
            ),
        ),
        migrations.AddField(
            model_name="docteur",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="docteur",
            name="zones",
            field=models.ManyToManyField(related_name="zones", to="surveillance.zone"),
        ),
    ]
