# Generated by Django 4.1.3 on 2022-11-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0002_alter_docteur_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docteur",
            name="email",
        ),
    ]
